/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiPlusMinus;

import com.sun.glass.events.KeyEvent;
import controles.ControlPlusMinus;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author David Hermosillo
 */
public class SumaEjemplosInterfaz extends javax.swing.JFrame {
    String numerosAleatorios[] = new String[5];
    String numerosRespuestas[] = new String[5];
    double startTime;
    GridBagConstraints gbc = new GridBagConstraints();
    ControlPlusMinus control = ControlPlusMinus.getSingletonInstance();
    /**
     * Creates new form sumaInter
     */
    public SumaEjemplosInterfaz() {
        initComponents();
        //se cambia el tamaño del panel y el frame para que este a la resolucion de la pantalla
        Toolkit tk = Toolkit.getDefaultToolkit();
        jPanel1.setFocusable(true);
        Dimension d = tk.getScreenSize();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setSize((int) d.getWidth(), (int) d.getHeight());
        jPanel1.setSize((int) d.getWidth(), (int) d.getHeight());
        this.add(jPanel1, BorderLayout.CENTER);
        //se centra el texPanel en el panel
        jPanel1.setLayout(new GridBagLayout());
        gbc.gridwidth = 2; // El área de texto ocupa dos columnas.
        gbc.gridheight = 2; // El área de texto ocupa 2 filas.
        gbc.weightx = 2;
        gbc.weightx = 0.1;
        gbc.fill = GridBagConstraints.CENTER;
        jPanel1.add(jPanel2, gbc);
        /*Se cambian los valores de los labels con los numeros aleatorias que se
        guardan en el arreglo numerosAleatorios y se inicia con el tiempo. */
        jLabel1.setText(control.numeroRandom());
        numerosAleatorios[0] = jLabel1.getText();

        jLabel2.setText(control.numeroRandom());
        numerosAleatorios[1] = jLabel2.getText();

        jLabel3.setText(control.numeroRandom());
        numerosAleatorios[2] = jLabel3.getText();

        jLabel4.setText(control.numeroRandom());
        numerosAleatorios[3] = jLabel4.getText();

        jLabel5.setText(control.numeroRandom());
        numerosAleatorios[4] = jLabel5.getText();
        jPanel1.setFocusable(true);
        jPanel1.requestFocus();
    }
        
    /** |
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cajaUno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cajaDos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cajaTres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cajaCuatro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cajaCinco = new javax.swing.JTextField();
        botonAceptarEjemplo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel1KeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setText("+3=");

        cajaUno.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cajaUno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaUno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaUnoFocusLost(evt);
            }
        });
        cajaUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUnoActionPerformed(evt);
            }
        });
        cajaUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaUnoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setText("+3=");

        cajaDos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cajaDos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaDosFocusLost(evt);
            }
        });
        cajaDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaDosKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("+3=");

        cajaTres.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cajaTres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaTresFocusLost(evt);
            }
        });
        cajaTres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaTresKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setText("+3=");

        cajaCuatro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cajaCuatro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaCuatroFocusLost(evt);
            }
        });
        cajaCuatro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaCuatroKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setText("+3=");

        cajaCinco.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cajaCinco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cajaCincoFocusLost(evt);
            }
        });
        cajaCinco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaCincoKeyTyped(evt);
            }
        });

        botonAceptarEjemplo.setBackground(new java.awt.Color(255, 255, 255));
        botonAceptarEjemplo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        botonAceptarEjemplo.setText("Aceptar");
        botonAceptarEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarEjemploActionPerformed(evt);
            }
        });
        botonAceptarEjemplo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonAceptarEjemploKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(botonAceptarEjemplo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cajaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cajaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cajaTres, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cajaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cajaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(cajaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(cajaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(cajaTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel11))
                    .addComponent(cajaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cajaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAceptarEjemplo)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    }//GEN-LAST:event_formKeyPressed
        
    private void jPanel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyTyped
        // TODO add your handling code here:
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_SPACE) {
            numerosRespuestas[0] = control.verificaciónTextField(cajaUno.getText());
            numerosRespuestas[1] = control.verificaciónTextField(cajaDos.getText());
            numerosRespuestas[2] = control.verificaciónTextField(cajaTres.getText());
            numerosRespuestas[3] = control.verificaciónTextField(cajaCuatro.getText());
            numerosRespuestas[4] = control.verificaciónTextField(cajaCinco.getText());
            
            cajaUno.setText("");
            cajaDos.setText("");
            cajaTres.setText("");
            cajaCuatro.setText("");
            cajaCinco.setText("");
        }
    }//GEN-LAST:event_jPanel1KeyTyped

    private void botonAceptarEjemploKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonAceptarEjemploKeyPressed

    }//GEN-LAST:event_botonAceptarEjemploKeyPressed

    private void botonAceptarEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarEjemploActionPerformed
        Instrucciones instrucciones = Instrucciones.getSingletonInstance();
        instrucciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAceptarEjemploActionPerformed

    private void cajaUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaUnoKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')){
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo numeros");
        }
    }//GEN-LAST:event_cajaUnoKeyTyped

    private void cajaUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUnoActionPerformed

    private void cajaDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaDosKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')){
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo numeros");
        }
    }//GEN-LAST:event_cajaDosKeyTyped

    private void cajaTresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaTresKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')){
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo numeros");
        }
    }//GEN-LAST:event_cajaTresKeyTyped

    private void cajaCuatroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCuatroKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')){
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo numeros");
        }
    }//GEN-LAST:event_cajaCuatroKeyTyped

    private void cajaCincoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCincoKeyTyped
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')){
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo numeros");
        }
    }//GEN-LAST:event_cajaCincoKeyTyped

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void cajaUnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaUnoFocusLost
        // TODO add your handling code here:
        int aleatorio = Integer.valueOf(jLabel1.getText());
        int respuesta = Integer.valueOf(cajaUno.getText());

        if (aleatorio + 3 == respuesta) {
            cajaUno.setBackground(Color.GREEN);
        } else {
            cajaUno.setBackground(Color.RED);
        }
    }//GEN-LAST:event_cajaUnoFocusLost

    private void cajaDosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaDosFocusLost
        int aleatorio = Integer.valueOf(jLabel2.getText());
        int respuesta = Integer.valueOf(cajaDos.getText());

        if (aleatorio + 3 == respuesta) {
            cajaDos.setBackground(Color.GREEN);
        } else {
            cajaDos.setBackground(Color.RED);
        }
    }//GEN-LAST:event_cajaDosFocusLost

    private void cajaTresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaTresFocusLost
        int aleatorio = Integer.valueOf(jLabel3.getText());
        int respuesta = Integer.valueOf(cajaTres.getText());

        if (aleatorio + 3 == respuesta) {
            cajaTres.setBackground(Color.GREEN);
        } else {
            cajaTres.setBackground(Color.RED);
        }
    }//GEN-LAST:event_cajaTresFocusLost

    private void cajaCuatroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaCuatroFocusLost
        int aleatorio = Integer.valueOf(jLabel4.getText());
        int respuesta = Integer.valueOf(cajaCuatro.getText());

        if (aleatorio + 3 == respuesta) {
            cajaCuatro.setBackground(Color.GREEN);
        } else {
            cajaCuatro.setBackground(Color.RED);
        }
    }//GEN-LAST:event_cajaCuatroFocusLost

    private void cajaCincoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cajaCincoFocusLost
        int aleatorio = Integer.valueOf(jLabel5.getText());
        int respuesta = Integer.valueOf(cajaCinco.getText());

        if (aleatorio + 3 == respuesta) {
            cajaCinco.setBackground(Color.GREEN);
        } else {
            cajaCinco.setBackground(Color.RED);
        }
    }//GEN-LAST:event_cajaCincoFocusLost

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SumaEjemplosInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SumaEjemplosInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SumaEjemplosInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SumaEjemplosInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SumaEjemplosInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarEjemplo;
    private javax.swing.JTextField cajaCinco;
    private javax.swing.JTextField cajaCuatro;
    private javax.swing.JTextField cajaDos;
    private javax.swing.JTextField cajaTres;
    private javax.swing.JTextField cajaUno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
